### ISSUE TITLE
[core] Reduce use of `any`

### ISSUE THREAD

**Issue by thepassle** [open-wc/custom-elements-json#14]
In some places there are quite a lot of `any` types used, just to get something working. It'd be nice to reduce the amount of `any` throughout the code.

Contributions are welcome here, if anybody is interested in contributing to this: Dont worry about the _entire_ codebase, whatever cleanup here is welcome 🙂

**Comment by AMoldskred** [comment]
I'll help you out!👋

**Comment by thepassle** [comment]
Awesome!

Please do let me know if you run into anything weird or need anything to get started 🙂 I very much followed the "make it work, then make it pretty" pattern 🙈 but if anything is unclear, I'm more than happy to help.
