### ISSUE TITLE
improve window.customElements.define

### ISSUE THREAD

**Issue by thepassle** [open-wc/custom-elements-json#37]
~~Currently only `customElements.define` is picked up as a `export` of `kind` `"custom-elements-definition"`. We should also pick up `window.customElements.define`.~~

It now naively handles `window.customElements.define`, but it would be nice to implement the helper code lars mentioned

**Comment by LarsDenBakker** [comment]
We have some helper code in the HMR plugin to lookup the reference path, so that you can even handle a reassigned custom element registry:

```
const x = window.customElements;

x.define('x-foo', XFoo);
```
