### ISSUE TITLE
analyzer: Globs in configuration file do not override CLI defaults

### ISSUE THREAD

**Issue by jsantell** [open-wc/custom-elements-json#61]
There are different results between using CLI globbing `custom-elements-manifest analyze --globs="src/*.js"` and via config file `{ globs: ["src/*.js"] }`.

The values [passed into globby](https://github.com/open-wc/custom-elements-manifest/blob/1b2bc1b5d32e4ddd219f25552fd75922461f6c19/packages/custom-elements-json-analyzer/src/index.ts#L91) differ here, such that when using the CLI, the glob paths are what is defined, plus some node_modules etc. filtering.

```js
 [
  'src/*.js',
  '!node_modules/**/*.*',
  '!bower_components/**/*.*',
  '!**/*.test.{js,ts}',
  '!**/*.suite.{js,ts}',
  '!**/*.config.{js,ts}'
]
```

The same defined in a configuration file results in the same set of globs, *plus* the CLI's default value for globbing:

```js
 [
  '**/*.{js,ts}', // <- these are CLI defaults
  '!**/.*.{js,ts}', // <- these are CLI defaults
  'src/*.js',
  '!node_modules/**/*.*',
  '!bower_components/**/*.*',
  '!**/*.test.{js,ts}',
  '!**/*.suite.{js,ts}',
  '!**/*.config.{js,ts}'
]
```

If globs are specified, I'd expect the same result regardless if they were via CLI or configuration file, and only use the default glob paths if neither specified.

**Comment by thepassle** [comment]
This should be fixed in the new version of the analyzer, please let me know if the problem still persists
