### ISSUE TITLE
analyzer: expose JSDoc default, types for all relevant tags

### ISSUE THREAD

**Issue by jsantell** [open-wc/custom-elements-json#63]
In the [original manifest analyzer](https://github.com/webcomponents/custom-elements-manifest), additional properties were supported for type and defaults for tags like `@cssprop`:

```
/**
 * @cssprop {<length>} [--my-prop=10px] My CSS property.
 */
```

Is there interest in supporting this in core?

**Comment by thepassle** [comment]
This is supported in the latest version of the analyzer https://github.com/open-wc/custom-elements-manifest/tree/master/packages/analyzer#supported-jsdoc
